#!/usr/bin/env python3
"""Create an isolated Python 3.12 environment; never modify the global installation."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import venv

ROOT = Path(__file__).resolve().parents[1]

def run(argv, **kwargs):
    subprocess.run([str(x) for x in argv], check=True, **kwargs)

def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--venv',type=Path)
    p.add_argument('--wheelhouse',type=Path,help='Directory generated by build_wheels.py')
    p.add_argument('--offline',action='store_true',help='Install only from wheelhouse')
    args=p.parse_args()
    if sys.version_info[:2] != (3,12):
        p.error('Use Python 3.12 for the verified dependency lock (py -3.12 on Windows).')
    data=Path(os.environ.get('LOCALAPPDATA',Path.home()/'AppData'/'Local')) if os.name=='nt' else Path(os.environ.get('XDG_DATA_HOME',Path.home()/'.local'/'share'))
    target=(args.venv or data/'dsh-document-reader'/'venv').resolve()
    if args.offline and not args.wheelhouse:p.error('--offline requires --wheelhouse')
    venv.EnvBuilder(with_pip=True).create(target)
    python=target/('Scripts/python.exe' if os.name=='nt' else 'bin/python')
    base=[python,'-m','pip','install','--disable-pip-version-check','-c',ROOT/'python/constraints.lock']
    if args.wheelhouse:
        wheelhouse=args.wheelhouse.resolve()
        manifest=json.loads((wheelhouse/'SHA256SUMS.json').read_text())
        for filename,digest in manifest.items():
            if Path(filename).name!=filename or hashlib.sha256((wheelhouse/filename).read_bytes()).hexdigest()!=digest:
                raise SystemExit('Wheel checksum validation failed.')
        run(base+['--no-index','--find-links',wheelhouse,'-r',ROOT/'python/requirements.txt'])
    else:
        run(base+['-r',ROOT/'python/requirements.txt'])
    run([python,'-I','-X','utf8',ROOT/'python/markitdown_bridge.py','--doctor'])
    print('\nPython environment ready. Set python.executable to:')
    print(python)

if __name__=='__main__':main()
